#!/usr/bin/python3
import os
from dotenv import load_dotenv

load_dotenv()
 
db_user = os.environ.get('db_user')
db_password = os.environ.get('db_password')
API_KEY = os.environ.get('api_key')
print(db_user)
print(db_password)
print(API_KEY)
